/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e5e9eb',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#111c2c',
        'on-primary': '#ffffff',
        'on-surface-variant': '#44474c',
        'on-primary-fixed': '#0b1d2d',
        'tertiary-container': '#1f2b30',
        'on-secondary-container': '#586377',
        'surface-container-low': '#f1f4f6',
        'secondary-container': '#d5e0f7',
        'on-tertiary-fixed': '#111d22',
        'inverse-surface': '#2d3133',
        'tertiary-fixed': '#d8e4eb',
        'on-surface': '#181c1e',
        'primary-fixed-dim': '#b7c8de',
        'outline-variant': '#c4c6cd',
        'on-tertiary': '#ffffff',
        'surface-container': '#ebeef0',
        'inverse-primary': '#b7c8de',
        'on-tertiary-fixed-variant': '#3c494e',
        'on-primary-container': '#8192a7',
        primary: '#041627',
        secondary: '#545f72',
        'primary-container': '#1a2b3c',
        'surface-container-highest': '#e0e3e5',
        'surface-dim': '#d7dadc',
        'on-primary-fixed-variant': '#38485a',
        'inverse-on-surface': '#eef1f3',
        'secondary-fixed': '#d8e3fa',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#bcc7dd',
        outline: '#74777d',
        'on-secondary': '#ffffff',
        'surface-variant': '#e0e3e5',
        tertiary: '#0a171b',
        'primary-fixed': '#d2e4fb',
        'error-container': '#ffdad6',
        'surface-tint': '#4f6073',
        'surface-bright': '#f7fafc',
        error: '#ba1a1a',
        'on-tertiary-container': '#869299',
        'on-secondary-fixed-variant': '#3c475a',
        background: '#f7fafc',
        surface: '#f7fafc',
        'tertiary-fixed-dim': '#bcc8cf',
        'on-background': '#181c1e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '64px',
        base: '4px',
        xl: '48px',
        sm: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
        xs: '4px',
        md: '16px',
        lg: '24px',
        'max-width-content': '800px',
      },
      maxWidth: {
        'max-width-content': '800px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
